export const NEXT_STEP = "NEXT_STEP";
export const BACK_STEP = "BACK_STEP";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const ADD_EDUCATION = "ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

export const ADD_SKILL = "ADD_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";

export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const ADD_SOCIAL = "ADD_SOCIAL";
export const UPDATE_SOCIAL = "UPDATE_SOCIAL";
export const DELETE_SOCIAL = "DELETE_SOCIAL";
